name: Deploy to Amazon EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Deploy to Amazon EC2
        uses: easingthemes/ssh-deploy@v5.0.2
        with:
          SOURCE: '.'
          TARGET: '/var/www/html/'
          EXCLUDE: '/.github/,/vendor/,/.env'

      - name: Deploy
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
